### ISSUE TITLE
Failed to resolve component

### ISSUE THREAD

**Issue by Sin1tar** [madebyfabian/vue-focus-visible#3] opened 2021-12-14 22:38 UTC
app.vue:
`
<script lang="ts" setup>
import { useNuxtApp } from '#app'

const app = useNuxtApp()
import('vue-focus-visible').then(({ FocusVisible }) => {
  if (FocusVisible) {
    console.log(FocusVisible)
    app.vueApp.use(FocusVisible)
  }
})
</script>

<template>
  <div v-focus-visible>
    <nuxt-page />
  </div>
</template>

`

Got this in the browser console:
`
Error while mounting app: TypeError: Cannot read properties of undefined (reading 'deep')
    at withDirectives (runtime-core.esm-bundler.js:3019)
    at Proxy._sfc_render (app.vue:16)
    at renderComponentRoot (runtime-core.esm-bundler.js:464)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:4332)
    at ReactiveEffect.run (reactivity.esm-bundler.js:160)
    at setupRenderEffect (runtime-core.esm-bundler.js:4458)
    at mountComponent (runtime-core.esm-bundler.js:4241)
    at processComponent (runtime-core.esm-bundler.js:4199)
    at patch (runtime-core.esm-bundler.js:3791)
    at mountSuspense (runtime-core.esm-bundler.js:772)
`

Using nuxt3 (vue3)

**Comment by madebyfabian** [comment] 2021-12-14 22:51
Hey there, thanks for creating the issue. I've tested the plugin with vue3, and also on nuxt2, so the issue on here should be the releatively new nuxt3, which I didn't get a chance to try out. Can you provide me a minimal reproduction repository where this issue happens? That would help a lot. Thanks in advance.

**Comment by Sin1tar** [comment] 2021-12-14 23:34
> Hey there, thanks for creating the issue. I've tested the plugin with vue3, and also on nuxt2, so the issue on here should be the releatively new nuxt3, which I didn't get a chance to try out. Can you provide me a minimal reproduction repository where this issue happens? That would help a lot. Thanks in advance.

Sure, here is https://github.com/SergeyMustafin/failedtorslvc (app.vue)
also tried connect vue-focus-visible with the following guide (https://v3.nuxtjs.org/docs/directory-structure/plugins), but also dont work

**Comment by madebyfabian** [comment] 2021-12-14 23:43
Thanks, will look into it asap :)

**Comment by madebyfabian** [comment] 2021-12-17 12:08
Update: I was able somehow able to get it to work with nuxt3. But since nuxt3 is still in development and there is actually a RFC in discussion to change the way vue plugins are installed into nuxt3, I would suggest to wait for the stable nuxt3 release. There is a lot that has changed between vue2, webpack, nuxt2 and vue3, vite and nuxt3 which may or not may be requires me to rewrite the plugin and or the docs. What I've done to get it to work is:

1. create the file `plugins/focus-visible.client.js` <- only works with .client in there
2. add this to the file
```js
import { defineNuxtPlugin } from '#app'
import FocusVisible from 'vue-focus-visible'

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.use(FocusVisible)
})
```
3. use it like this in `app.vue`
```vue
<template>
  <main v-focus-visible>
    <h1>Test</h1>
    <a href="#">Haha</a>
    <button>lol</button>
  </main>
</template>
```
Issue is that it does only work until the next page refresh... Then nuxt spits out this:
<img width="700" alt="Bildschirmfoto 2021-12-17 um 13 06 40" src="https://user-images.githubusercontent.com/32813692/146542469-c1ee8767-531c-4fdb-b97a-e89197b0426d.png">
and the console:
<img width="799" alt="Bildschirmfoto 2021-12-17 um 13 07 34" src="https://user-images.githubusercontent.com/32813692/146542590-23b9f771-9d9b-4490-8110-31b6235cf5cf.png">

and I was not able to remove this error. Maybe you can also try installing it in this way and see if you find any reason for this issue.

**Comment by madebyfabian** [comment] 2021-12-17 12:10
Also, look at those similar issues
https://github.com/nuxt/nuxt.js/issues/12660 
https://github.com/nuxt/nuxt.js/issues/11884
https://github.com/nuxt/nuxt.js/issues/12729
https://github.com/nuxt/nuxt.js/issues/12713

**Comment by madebyfabian** [comment] 2021-12-17 12:18
Update 2: It works! Found the issue in https://github.com/nuxt/nuxt.js/issues/12713. In nuxt3, it seems you need to register a plugin with directives 2 times, as a plugin and then as a server-only empty directive in the config.

So the final solution is:
1. create the file `plugins/focus-visible.client.js` <- only works with .client in there
2. add this to the file
```js
import { defineNuxtPlugin } from '#app'
import FocusVisible from 'vue-focus-visible'

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.use(FocusVisible)
})
```
3. add this to your `nuxt.config.ts`:
```js
export default defineNuxtConfig({
  // ...
  vue: {
    compilerOptions: {
      directiveTransforms: {
        'focus-visible': () => ({
          props: [],
          needRuntime: true
        })
      }
    }
  }
})
``` 
4. use it like this in `app.vue`
```vue
<template>
  <main v-focus-visible>
    <h1>Test</h1>
    <a href="#">Haha</a>
    <button>lol</button>
  </main>
</template>
```

will update the docs for vue-focus-visible and close this ticket. Thanks for coming up with this!

**Closed as completed by madebyfabian** 2021-12-17 12:18 UTC
Labels: bug
